// generated by stringer -type=BackupBrand; DO NOT EDIT

package machine

import "fmt"

const _BackupBrand_name = "BackupBrandNoneBackupBrandBaculaBackupBrandSEPBackupBrandBackupPCBackupBrandFile"

var _BackupBrand_index = [...]uint8{0, 15, 32, 46, 65, 80}

func (i BackupBrand) String() string {
	if i < 0 || i >= BackupBrand(len(_BackupBrand_index)-1) {
		return fmt.Sprintf("BackupBrand(%d)", i)
	}
	return _BackupBrand_name[_BackupBrand_index[i]:_BackupBrand_index[i+1]]
}
