// generated by stringer -type=BackupType; DO NOT EDIT

package machine

import "fmt"

const _BackupType_name = "BackupTypeNoBackupTypeYesBackupTypeNotNeededBackupTypeNotResponsible"

var _BackupType_index = [...]uint8{0, 12, 25, 44, 68}

func (i BackupType) String() string {
	if i < 0 || i >= BackupType(len(_BackupType_index)-1) {
		return fmt.Sprintf("BackupType(%d)", i)
	}
	return _BackupType_name[_BackupType_index[i]:_BackupType_index[i+1]]
}
